
name: CD Web

on:
  push:
    branches: [ main ]

env:
  CI: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        echo "::set-env name=BUCKET_NAME::${{ secrets.BUCKET_NAME }}"
        echo "::set-env name=CLOUDFRONT_ID::${{ secrets.CLOUDFRONT_ID }}"
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Setup Node version
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build React App
      id: build
      run: |
        yarn install && yarn build
    - name: Deploy to AWS
      id: deploy
      run: |
        aws s3 sync ./build/ s3://$BUCKET_NAME
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"