name: CD Api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Node version
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install aws cdk
      run: npm install -g aws-cdk

    - name: Build App
      id: build
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Install CDK dependency
      id: bootstrap
      working-directory: './infra'
      run: |
        yarn install --frozen-lockfile

    - name: Bootstrap CDK
      id: bootstrap
      working-directory: './infra'
      run: |
        cdk synth -c domain=cda.sh -c subdomain=www

    - name: Deploy to aws
      id: deploy
      working-directory: './infra'
      run: |
        cdk deploy --require-approval never -c domain=cda.sh -c subdomain=www
